plugins { id 'com.android.application' }
android {
    namespace 'com.zeus97x.zbattle'
    compileSdk 35
    defaultConfig {
        applicationId 'com.zeus97x.zbattle'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }
    sourceSets { main { assets.srcDirs = ['../ZBattle-ZPet-Assets/assets'] } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
